# Form implementation generated from reading ui file 'C:\Users\cruiz\OneDrive\Documents\Github\HakotX-UI\ui\dialog\About.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_aboutDialog(object):
    def setupUi(self, aboutDialog):
        aboutDialog.setObjectName("aboutDialog")
        aboutDialog.resize(400, 300)
        aboutDialog.setStyleSheet("QLabel#titleLabel {\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"      }\n"
"      QLabel#versionLabel {\n"
"        color: #555;\n"
"      }\n"
"      QLabel#linkLabel {\n"
"        color: #0066cc;\n"
"        text-decoration: underline;\n"
"      }\n"
"      QLabel#linkLabel:hover {\n"
"        color: #004499;\n"
"      }")
        self.verticalLayout = QtWidgets.QVBoxLayout(aboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.versionLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.versionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout.addWidget(self.versionLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.descriptionLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.authorLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.authorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout.addWidget(self.authorLabel)
        self.linkLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.linkLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.linkLabel.setOpenExternalLinks(True)
        self.linkLabel.setObjectName("linkLabel")
        self.verticalLayout.addWidget(self.linkLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.licenseLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.licenseLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.licenseLabel.setObjectName("licenseLabel")
        self.verticalLayout.addWidget(self.licenseLabel)
        self.copyrightLabel = QtWidgets.QLabel(parent=aboutDialog)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.verticalLayout.addWidget(self.copyrightLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.closeButton = QtWidgets.QPushButton(parent=aboutDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(aboutDialog)
        self.closeButton.clicked.connect(aboutDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(aboutDialog)

    def retranslateUi(self, aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        aboutDialog.setWindowTitle(_translate("aboutDialog", "About HakotX"))
        self.titleLabel.setText(_translate("aboutDialog", "HakotX - ONU Scanner & Viewer"))
        self.versionLabel.setText(_translate("aboutDialog", "Version: 1.0.0"))
        self.descriptionLabel.setText(_translate("aboutDialog", "A powerful Onu Scanner and Viewer tailored only for BCCTV."))
        self.authorLabel.setText(_translate("aboutDialog", "Developed by AlienWolfX"))
        self.linkLabel.setText(_translate("aboutDialog", "<a href=\"https://github.com/AlienWolfX\">https://github.com/AlienWolfX</a>"))
        self.licenseLabel.setText(_translate("aboutDialog", "License: MIT"))
        self.copyrightLabel.setText(_translate("aboutDialog", "© 2025 AlienWolfX. All rights reserved."))
        self.closeButton.setText(_translate("aboutDialog", "Close"))
