# Form implementation generated from reading ui file 'C:\Users\cruiz\OneDrive\Documents\Github\HakotX-UI\ui\dialog\Edit_Record.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditRecordDialog(object):
    def setupUi(self, EditRecordDialog):
        EditRecordDialog.setObjectName("EditRecordDialog")
        EditRecordDialog.resize(500, 268)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditRecordDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=EditRecordDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_ip = QtWidgets.QLabel(parent=self.groupBox)
        self.label_ip.setObjectName("label_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ip)
        self.ipEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.ipEdit.setObjectName("ipEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ipEdit)
        self.label_mac = QtWidgets.QLabel(parent=self.groupBox)
        self.label_mac.setObjectName("label_mac")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_mac)
        self.macEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.macEdit.setObjectName("macEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.macEdit)
        self.label_ssid24 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_ssid24.setObjectName("label_ssid24")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ssid24)
        self.ssid24Edit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.ssid24Edit.setObjectName("ssid24Edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ssid24Edit)
        self.label_ssid5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_ssid5.setObjectName("label_ssid5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ssid5)
        self.ssid5Edit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.ssid5Edit.setObjectName("ssid5Edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ssid5Edit)
        self.label_pass24 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_pass24.setObjectName("label_pass24")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_pass24)
        self.pass24Edit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.pass24Edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pass24Edit.setObjectName("pass24Edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pass24Edit)
        self.label_pass5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_pass5.setObjectName("label_pass5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_pass5)
        self.pass5Edit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.pass5Edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pass5Edit.setObjectName("pass5Edit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pass5Edit)
        self.label_source = QtWidgets.QLabel(parent=self.groupBox)
        self.label_source.setObjectName("label_source")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_source)
        self.sourceEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.sourceEdit.setReadOnly(True)
        self.sourceEdit.setObjectName("sourceEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sourceEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=EditRecordDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditRecordDialog)
        self.buttonBox.accepted.connect(EditRecordDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EditRecordDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditRecordDialog)

    def retranslateUi(self, EditRecordDialog):
        _translate = QtCore.QCoreApplication.translate
        EditRecordDialog.setWindowTitle(_translate("EditRecordDialog", "Edit ONU Record"))
        self.groupBox.setTitle(_translate("EditRecordDialog", "ONU Details"))
        self.label_ip.setText(_translate("EditRecordDialog", "IP Address:"))
        self.label_mac.setText(_translate("EditRecordDialog", "MAC Address:"))
        self.label_ssid24.setText(_translate("EditRecordDialog", "SSID (2.4GHz):"))
        self.label_ssid5.setText(_translate("EditRecordDialog", "SSID (5GHz):"))
        self.label_pass24.setText(_translate("EditRecordDialog", "Password (2.4GHz):"))
        self.label_pass5.setText(_translate("EditRecordDialog", "Password (5GHz):"))
        self.label_source.setText(_translate("EditRecordDialog", "Source:"))
